# CI/CD Main workflow สำหรับ build และ deploy แอปพลิเคชัน restaurant
name: CI/CD Main

# กำหนด trigger เมื่อมี push ไปยัง branch main
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # ดึง source code จาก repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # สร้าง Docker image สำหรับ Spring Boot backend
      - name: Build Spring Boot Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant-backend:latest -f restaurant/Dockerfile restaurant

      # สร้าง Docker image สำหรับ Vue.js frontend
      - name: Build Vue.js Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant-frontend:latest -f frontend/Dockerfile frontend

      # เข้าสู่ระบบ Docker Hub ด้วย credentials ที่เก็บใน secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ส่ง Docker images ที่สร้างขึ้นไปยัง Docker Hub
      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-frontend:latest

      # สร้าง tag ใหม่โดยใช้เวลาปัจจุบันและ push tag ไปยัง repository
      - name: Generate and Push Tag
        run: |
          TAG="v$(date +'%Y.%m.%d.%H%M%S')" 
          git tag $TAG
          git push origin $TAG
